<?= $this->extend('public/layout') ?>
<?= $this->section('content') ?>
<section class="page-hero"><div class="container text-center"><h1>Our Electrical Services</h1><p>Comprehensive electrical solutions for residential, commercial, and industrial needs.</p></div></section>
<?php $groups = [
['Residential Services','fa-home',[['Electrical Wiring','New wiring, rewiring, inspections, and code-compliance updates.'],['Panel Upgrades','Panel replacement, circuit breakers, and capacity improvements.'],['Lighting Solutions','Indoor, outdoor, security, and energy-efficient LED lighting.'],['Smart Home Automation','Smart switches, controls, and energy monitoring.'],['EV Charging Stations','Home charger installation and electrical capacity checks.'],['Electrical Repairs','Troubleshooting for outlets, switches, and fixtures.']]],
['Commercial Services','fa-building',[['Commercial Wiring','Installations for offices, retail spaces, and buildings.'],['Power Distribution','Distribution panels, transformers, and backup power systems.'],['Security & Data Systems','Cameras, access controls, alarms, and cabling.'],['Industrial Electrical','Machine wiring, control systems, and industrial lighting.'],['Maintenance Services','Inspections, maintenance, and equipment testing.'],['Energy Efficiency','Energy audits, LED retrofits, and power improvements.']]],
['Solar & Renewable Energy','fa-solar-panel',[['Solar Panel Installation','System design, installation, permits, and grid connection.'],['Energy Storage Systems','Battery storage and backup power solutions.'],['Energy Consultation','Site assessment, energy analysis, and planning.'],['System Maintenance','Monitoring, cleaning, maintenance, and support.']]]]; ?>
<?php foreach ($groups as $index => $group): ?><section class="section-padding <?= $index % 2 === 0 ? 'bg-light-custom' : '' ?>"><div class="container"><div class="section-title"><h2><i class="fas <?= esc($group[1]) ?> text-warning me-2"></i><?= esc($group[0]) ?></h2></div><div class="row g-4"><?php foreach ($group[2] as $item): ?><div class="col-lg-4 col-md-6"><div class="card h-100 p-4 feature-item"><h4><?= esc($item[0]) ?></h4><p class="text-muted mb-0"><?= esc($item[1]) ?></p></div></div><?php endforeach ?></div></div></section><?php endforeach ?>
<section class="emergency-section"><div class="container text-center"><h2><i class="fas fa-triangle-exclamation text-warning me-2"></i>Emergency Electrical Support</h2><p>Contact our team immediately for dangerous electrical faults, outages, or safety concerns.</p><a class="btn btn-warning btn-lg" href="<?= site_url('contact') ?>">Contact Us</a></div></section>
<?= $this->endSection() ?>
